set(PLATFORM_X11 OFF)
set(PLATFORM_WAYLAND OFF)
set(PLATFORM_MACOS OFF)
set(PLATFORM_WINDOWS OFF)

if(APPLE)
    set(PLATFORM_MACOS ON)
    set(LIVE2D_PLATFORM_DIR "macos-universal")
elseif(WIN32)
    set(PLATFORM_WINDOWS ON)
    set(LIVE2D_PLATFORM_DIR "windows/${CMAKE_SYSTEM_PROCESSOR}")
elseif(UNIX)
    set(LIVE2D_PLATFORM_DIR "linux-${CMAKE_SYSTEM_PROCESSOR}")

    find_package(X11 COMPONENTS Xext Xtst)
    if(X11_FOUND AND X11_Xext_FOUND AND X11_Xtst_FOUND)
        set(PLATFORM_X11 ON)
    elseif(X11_FOUND AND X11_Xext_FOUND)
        message(WARNING "X11 found but libXtst missing — X11 mouse tracking disabled. "
                        "Install libxtst-dev (Debian/Ubuntu) or libxtst (Arch).")
    endif()

    find_package(PkgConfig)
    if(PKG_CONFIG_FOUND)
        pkg_check_modules(WAYLAND_CLIENT wayland-client)
        if(WAYLAND_CLIENT_FOUND)
            set(PLATFORM_WAYLAND ON)
        endif()
    endif()
endif()

message(STATUS "Platform detection:")
message(STATUS "  macOS:   ${PLATFORM_MACOS}")
message(STATUS "  Windows: ${PLATFORM_WINDOWS}")
message(STATUS "  X11:     ${PLATFORM_X11}")
message(STATUS "  Wayland: ${PLATFORM_WAYLAND}")
